//ImageProfile
export const REQUEST_IMAGE_PROFILE = 'REQUEST_IMAGE_PROFILE';
export const RECEIVE_IMAGE_PROFILE = 'RECEIVE_IMAGE_PROFILE';
export const FAIL_IMAGE_PROFILE = 'FAIL_IMAGE_PROFILE';

export const REQUEST_SINGLE_IMAGE_PROFILE = 'REQUEST_SINGLE_IMAGE_PROFILE';
export const RECEIVE_SINGLE_IMAGE_PROFILE = 'RECEIVE_SINGLE_IMAGE_PROFILE';
export const FAIL_SINGLE_IMAGE_PROFILE = 'FAIL_SINGLE_IMAGE_PROFILE';
//Global
export const IS_FETCHING = 'IS_FETCHING';